language: java
sudo: required
script: mvn test
after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report package dockerfile:build -DpushImage
jdk:
  - oraclejdk8
services:
  - docker